## Practice Task

In this practice task, we have been tasked to assist a group of biologists in their research on the impact of sports on the hormone levels of a group of mice. They have supplied us with a dataset containing information on hormone values from various observations. Our role, as data scientists, is to clean and prepare the dataset for machine learning analysis.

----


The tasks involved in this process are as follows:


*   Removing rows with missing or null values.
*   Applying standard scaling using the scikit-learn StandardScaler to standardize the features.

### Importing the modules

In [1]:
import pandas as pd
from sklearn.preprocessing import StandardScaler

### Importing the dataset

In [2]:
data = pd.read_csv("Practice_task_data.csv")

In [3]:
data.head()

,Prolactin,Testosterone,Estradiol,Ghrelin,Leptin,Growth Hormone,Thyroid hormones,Cortisol,Glucagon,Insulin
0,60.858987,87.344148,36.548465,51.606929,73.392630,104.607003,58.929211,27.558829,37.477667,8.508406
1,45.372350,20.377196,47.919643,3.786530,68.394583,84.649699,78.608607,80.188358,45.654386,3.183478
2,9.568807,33.239611,16.617455,56.309311,24.299365,23.293599,42.872505,22.585599,1.240089,13.115196
3,59.330341,84.822243,36.390014,62.697380,83.580213,87.102520,66.446913,9.445333,29.833509,25.341548
4,49.787001,91.942422,44.813039,51.875910,79.318703,90.485978,70.058949,18.792459,39.268871,6.729101

### Check the shape of the dataset

In [4]:
data.shape

(6000, 10)

### Removing the rows with  Nan values in the dataset

In [5]:
data = data.dropna()

### Check the shape of the data frame again to check how many rows are deleted.

In [6]:
data.shape

(5993, 10)

### Use the sklearn StandardScaler to scale the dataset features

In [7]:
scaled_values = StandardScaler().fit_transform(data)

In [8]:
scaled_values

array([[ 0.94994767,  2.20899889, -0.14436844, ..., -0.68522405,
        -0.02837787, -0.91364543],
       [ 0.39086329, -1.24805046,  0.32983622, ...,  1.71837271,
         0.44457184, -1.28536727],
       [-0.90168344, -0.58405121, -0.9755381 , ..., -0.91235207,
        -2.12439624, -0.59205533],
       ...,
       [ 1.12753529,  1.97096658, -0.58443986, ..., -1.29795609,
         0.24191754, -0.83651236],
       [-0.31393391, -0.02730087, -0.05641947, ...,  1.05516304,
         0.28225798,  1.48110062],
       [ 0.65036635, -0.60129391,  1.4866539 , ...,  1.83063045,
        -0.17259212, -0.96765287]])

### Create a Dataframe of the scaled values

In [9]:
df = pd.DataFrame(scaled_values, columns = data.columns)

In [10]:
df

,Prolactin,Testosterone,Estradiol,Ghrelin,Leptin,Growth Hormone,Thyroid hormones,Cortisol,Glucagon,Insulin
0,0.949948,2.208999,-0.144368,0.289141,0.608911,1.294795,0.379820,-0.685224,-0.028378,-0.913645
1,0.390863,-1.248050,0.329836,-1.672892,0.349125,0.820382,1.060605,1.718373,0.444572,-1.285367
2,-0.901683,-0.584051,-0.975538,0.482076,-1.942835,-0.638137,-0.175642,-0.912352,-2.124396,-0.592055
3,0.894762,2.078810,-0.150976,0.744174,1.138436,0.878689,0.639886,-1.512470,-0.470524,0.261440
4,0.550237,2.446377,0.200284,0.300177,0.916933,0.959119,0.764840,-1.085585,0.075227,-1.037855
...,...,...,...,...,...,...,...,...,...,...
5988,1.000352,0.018608,0.736883,-1.214801,1.060358,0.919824,0.672250,1.183444,-0.024519,-0.780492
5989,1.729987,-0.187634,1.505287,-1.671073,2.019124,0.881320,0.772173,2.047359,0.903010,-1.167434
5990,1.127535,1.970967,-0.584440,0.872514,0.514588,0.819493,0.106391,-1.297956,0.241918,-0.836512
5991,-0.313934,-0.027301,-0.056419,-0.004964,-0.061284,-1.103150,-1.619896,1.055163,0.282258,1.481101
5992,0.650366,-0.601294,1.486654,-1.238683,0.542610,0.593449,1.178493,1.830630,-0.172592,-0.967653